# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'rails'
gem 'sinatra'
gem 'dotenv-rails', groups: [:development, :test]
ruby '2.5.1'
gem 'pry'
gem  'shotgun'
